### ISSUE TITLE
Fetch & Render Api 

### ISSUE THREAD

**Issue by RicardoBachmann** [RicardoBachmann/capstone-project#1]
## Value proposition

**As a** user,
**I want to** see a list of PGL-Partners locations in Detroit.
**so that** i can get an overview about the scale of camera surveillance.

## Description
<img width="374" alt="user_story_01" src="https://user-images.githubusercontent.com/55979464/175260536-eda3d7d7-d2de-4341-b1b5-cc1e1e04fade.png" width=320px>

## Acceptance criteria: 

- [ ] Display business name's from Api
- [ ] Ordered list by date 
- [ ] Fixed PGL Header 

## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Setup a Data file
- [ ] Fetch Api 
- [ ] Render the PGL-Partners in an list

**Comment by PReichetanz** [comment]
Hello Ricardo,
that's a good start!

Some questions which came to my mind:
- What does the "order by date" has to do with the business name displayed? I just don't get what kind of date is menat here: foundation of company? when it was added to the API?
- What do you need a data file for?
- What happens if the list is longer than the screen height?
- Is it correct that some name occur multiple times?

**Comment by RicardoBachmann** [comment]
Hey Paul, 
thank you for your notes! 

1) In the end I want to show in a kind of timeline, how expand the surveillance over the last 6 years (The Dataset starts with location 1 at 2016).
2) Yesterday i found an API with the partners locations. The days before I planed to import an cvs or geojson data file. Not sure now what's the best format or way for display the Dataset. I guess a cvs or geojson file can't fails in the end and may be safer to plan?
3) Yes! there are some names/locations multiple times but in different areas.
4) hmm good point! Should i go with the cvs or geojson Dataset?
