### ISSUE TITLE
Visualize Data on a Map

### ISSUE THREAD

**Issue by RicardoBachmann** [RicardoBachmann/capstone-project#2]
## Value proposition

**As a** user,
**I want to see the camera locations on a map,
**so that** i can explore the various areas in the city.

## Description
<img width="291" alt="Bildschirmfoto 2022-06-23 um 12 06 25" src="https://user-images.githubusercontent.com/55979464/175274681-0c0daa02-7183-4d7f-928e-1a5fdd7b7290.png"width=320px>

## Acceptance criteria

- [ ] Display locations as points on the map 

## Complexity

Large

## Tasks

- [ ] Create branch
- [ ] Setup deck.gl framework  
- [ ] Setup mapbox-gl js 
- [ ] Display the locations as points on the map
- [ ] Display the business names from the locations

**Comment by lkk95** [comment]
Looks good to me 👍🏼 
Maybe you can reword the US to "for navigating around Detroit", in my opinion that sounds better, but this is personal preference ;)
