### ISSUE TITLE
5) Searchbar for Participant Data

### ISSUE THREAD

**Issue by RicardoBachmann** [RicardoBachmann/capstone-project#9]
## Value proposition

**As a** user,
**I want to** search participants through API-Data,  
**so that** I can find specific locations of my interests. 

## Description

<img width="635" alt="user_story_05" src="https://user-images.githubusercontent.com/55979464/178704520-51f8e03d-461e-45ab-a1b6-3752f2277904.png" width=320px>

## Acceptance criteria

- [x] Implement input field above `ParticipantCard`
- [x] Placeholder text in searchbar for accessibility
- [x] Only cards they match with the input content should displayed 

## Complexity

Medium 

## Tasks

- [x] Create branch `searchbar-participant`
- [x] Create input field
- [x] Create functionality with connecting API-Dataset
